query patients {
    patients {
        name {
            first
            last
        }
        phone {
            home
        }
        birthDate
        lastUpdated
        gender
        practitioner {
            name {
                full
            }
        }
    }
}
